image: docker:stable

variables:
  DOCKER_REGISTRY: $CI_REGISTRY/$CI_PROJECT_NAMESPACE
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - only_tag

build:
  stage: build
  only:
    refs:
      - master
  script:
    - |
      docker build \
        --build-arg DOCKER_REGISTRY=$DOCKER_REGISTRY \
        --tag $CI_REGISTRY_IMAGE:master .
    - docker push $CI_REGISTRY_IMAGE:master

only_tag:
  stage: only_tag
  rules:
    - if: '$CI_COMMIT_TAG != null'
  script:
    - |
      docker build \
        --build-arg DOCKER_REGISTRY=$DOCKER_REGISTRY \
        --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
